### ISSUE TITLE
Add features: task 3

### ISSUE THREAD

**Issue by HalfSealHalfCat** [PrusakovMS/infa_2020_prusakov#1]
[In task 3](https://github.com/PrusakovMS/infa_2020_prusakov/blob/main/4%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0/%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D1%87%D0%BA%D0%B0.py)

1. Transparency is only body feature for ghosts, correct the output.
2. Add some sort of ghosts animation.
3. Provide an ability to change house size, colour, roof and window shapes, and also random window lightening (the last is interesting in terms of pic animation).

**Comment by PrusakovMS** [comment]
I have added body transparency for ghosts, random window lightening and appearance of ghosts. The picture is now perfect, i think.)
